### ISSUE TITLE
为什么进去后正常左上角显示开始，不停刷新页面才会显示开始按钮

### ISSUE THREAD

**Issue by BMWM4C** [Xu22Web/tech-study-js#1]
只有不停刷新页面左上角才会出现开始界面，大佬知道是啥情况嘛

**Comment by Xu22Web** [comment]
> 整个`学习面板`还是`学习按钮`?
1. 如果是`开始学习`按钮的话，是在登录完成后，获取完积分信息才显示显示
2. 确保没有开启`运行隐藏`按钮，开启的话会隐藏面板
3. 反馈时，尽量看下有无控制台报错，适当加入运行环境的说明

**Comment by Xu22Web** [comment]
> 是否仍存在问题？ @BMWM4C 

没有的话，我近期会关闭这个`issue`的评论
