### ISSUE TITLE
2023/1/1无法使用呜呜呜求破，看开发者工具显示无法加载来源映射

### ISSUE THREAD

**Issue by LittleFatFishLoveEatingLittleDragonBabe** [Xu22Web/tech-study-js#10]
开发者工具显示如下：
iflow-api.xuexi.cn/logflow/api/v1/pclog:1          Failed to load resource: net::ERR_EMPTY_RESPONSE
index.html:1 Uncaught (in promise) 0
DevTools 无法加载来源映射：无法加载 chrome-extension://mnjkfcgamfdbjnegbggclolippgppgcc/md5.min.js.map 的内容：系统错误: net::ERR_BLOCKED_BY_CLIENT
 POST https://iflow-api.xuexi.cn/logflow/api/v1/pclog net::ERR_TIMED_OUT

**Comment by Xu22Web** [comment]
@LittleFatFishLoveEatingLittleDragonBabe 
官方好像把`每周答题`去掉了，不知道你们是不是这个情况，如果是，我得修改下代码

**Comment by zoomshine** [comment]
> 



> @LittleFatFishLoveEatingLittleDragonBabe 官方好像把`每周答题`去掉了，不知道你们是不是这个情况，如果是，我得修改下代码

是的，已经没有每周答题了

**Comment by sunyi369** [comment]
> @LittleFatFishLoveEatingLittleDragonBabe 官方好像把`每周答题`去掉了，不知道你们是不是这个情况，如果是，我得修改下代码

大佬有tg交流群么

**Comment by Xu22Web** [comment]
@sunyi369 
暂时还没有

**Comment by Xu22Web** [comment]
@sunyi369 @zoomshine @LittleFatFishLoveEatingLittleDragonBabe 
新版脚本 [tech-study-js v1.4.0](https://github.com/Xu22Web/tech-study-js/releases/tag/v1.4.0) 已经发布，问题基本得到解决

如仍存在问题，可以继续反馈。
