### ISSUE TITLE
在哪呀

### ISSUE THREAD

**Issue by Duanyichen746** [Xu22Web/tech-study-js#14]
去 pushplus 账号

_Originally posted by @Xu22Web in https://github.com/Xu22Web/tech-study-js/issues/12#issuecomment-1420264163_

**Comment by Xu22Web** [comment]
@Duanyichen746 
去这里注册下 https://www.pushplus.plus/

**Comment by Duanyichen746** [comment]
非常感谢，已经可以使用了。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Xu ***@***.***>
发送时间: 2023年2月14日 18:39
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Xu22Web/tech-study-js] 在哪呀 (Issue #14)


Closed #14<https://github.com/Xu22Web/tech-study-js/issues/14> as completed.

―
