### ISSUE TITLE
大佬，网页版用油猴，显示错误

### ISSUE THREAD

**Issue by ailoading** [Xu22Web/tech-study-js#16]
![截图20230214091522](https://user-images.githubusercontent.com/48814761/218612903-530e97fc-dd02-4ec2-a7f7-75b2e89aca5d.jpg)

**Comment by Xu22Web** [comment]
应该是未复制完全，我这边没有问题，请尝试重新复制

**Comment by ailoading** [comment]
> 

![截图20230214185815](https://user-images.githubusercontent.com/48814761/218716911-d0debc86-8af4-4284-a8ef-1d072ad5972e.jpg)
换了Chrome浏览器，用油猴，Ctrl A  、 Ctrl C  、Ctrl V ，弹了更多错误

**Comment by Xu22Web** [comment]
警告而已，能用就行

**Comment by ailoading** [comment]
谢谢，我再试试看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xu22Web/tech-study-js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月14日(星期二) 晚上7:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xu22Web/tech-study-js] 大佬，网页版用油猴，显示错误 (Issue #16)





 
警告而已，能用就行
