### ISSUE TITLE
远程推送

### ISSUE THREAD

**Issue by msnpersonone** [Xu22Web/tech-study-js#23]
大佬，请问远程推送怎么使用
我关注了pushplus，激活消息，打开了消息通知，在脚本中填入token保存，但提示我远程推送失败

**Comment by major-tom8** [comment]
油猴版只需要在0,id:"",scheduleList:[],pushToken:这个地方填token其他不要动

**Comment by leechee67** [comment]
> 油猴版只需要在0,id:"",scheduleList:[],pushToken:这个地方填token其他不要动

大佬 复制之后在编辑器里查找 搜索不到这个地方啊

**Comment by msnpersonone** [comment]
> 油猴版只需要在0,id:"",scheduleList:[],pushToken:这个地方填token其他不要动

谢谢，已解决，但功能和我想的不一样，我想的是，我在电脑上一直开着网页，每天九点前，如果我没有手动扫码登陆，那远程推送就把登录二维码给我，这样我就可以实现远程，不在电脑前的情况下登录，目前我开了远程，开了定时刷新，开了自动开始，没有达到此效果
或者，能判断周六周日每天九点自动推送二维码也可以

**Comment by leechee67** [comment]
> > 油猴版只需要在0,id:"",scheduleList:[],pushToken:这个地方填token其他不要动
> 
> 谢谢，已解决，但功能和我想的不一样，我想的是，我在电脑上一直开着网页，每天九点前，如果我没有手动扫码登陆，那远程推送就把登录二维码给我，这样我就可以实现远程，不在电脑前的情况下登录，目前我开了远程，开了定时刷新，开了自动开始，没有达到此效果 或者，能判断周六周日每天九点自动推送二维码也可以

能告诉我是怎么找到这一串代码的吗

**Comment by msnpersonone** [comment]
> > > 油猴版只需要在0,id:"",scheduleList:[],pushToken:这个地方填token其他不要动
> > 
> > 
> > 谢谢，已解决，但功能和我想的不一样，我想的是，我在电脑上一直开着网页，每天九点前，如果我没有手动扫码登陆，那远程推送就把登录二维码给我，这样我就可以实现远程，不在电脑前的情况下登录，目前我开了远程，开了定时刷新，开了自动开始，没有达到此效果 或者，能判断周六周日每天九点自动推送二维码也可以
> 
> 能告诉我是怎么找到这一串代码的吗

能直接搜索到，搜索不到可能你符号中英文有误

**Comment by Xu22Web** [comment]
@leechee67 
新版本可以这样设置
![image](https://user-images.githubusercontent.com/63391451/227832829-ad49fb62-6935-400d-821c-cd6a87214507.png)
