### ISSUE TITLE
一直显示“等待中”

### ISSUE THREAD

**Issue by Lib-ChenS** [Xu22Web/tech-study-js#24]
大佬，请问一直显示“等待中”，如何解决？

**Comment by Lib-ChenS** [comment]
![image](https://user-images.githubusercontent.com/93749682/226081360-b88299f6-fbaa-42f3-90a0-02328727fb8a.png)

**Comment by cagedli** [comment]
js里面的https://pc-proxy-api.xuexi.cn/api/score/days/listScoreProgress?sence=score&deviceType=2修改为https://pc-proxy-api.xuexi.cn/delegate/score/days/listScoreProgress?sence=score&deviceType=2

**Comment by Lib-ChenS** [comment]
解决啦！非常感谢🤣

**Comment by cbcgame** [comment]
请问大神，要怎么用JS编辑，然后替换网址，在线等回复
![image](https://user-images.githubusercontent.com/128456518/226537067-74245554-9555-450a-b884-b8897f882993.png)

**Comment by Xu22Web** [comment]
已回复，参考 #25

**Comment by RoeGross** [comment]
没用呢，我下了最新的js 也没用 也是一直等待中
