### ISSUE TITLE
一直显示：“等待中”，大佬说了换地址，但是不会JS编辑替换

### ISSUE THREAD

**Issue by cbcgame** [Xu22Web/tech-study-js#25]
![image](https://user-images.githubusercontent.com/128456518/226538370-59abc4cf-a13a-4c52-a8f6-ef0cc973c741.png)

js里面的https://pc-proxy-api.xuexi.cn/api/score/days/listScoreProgress?sence=score&deviceType=2
修改为 https://pc-proxy-api.xuexi.cn/delegate/score/days/listScoreProgress?sence=score&deviceType=2

请问大神，要怎么用JS编辑，然后替换网址，在线等回复

**Comment by Xu22Web** [comment]
更新了，最近有点忙，不好意思 详见[Release v1.6.0](https://github.com/Xu22Web/tech-study-js/releases/tag/v1.6.0) 
@cbcgame

**Comment by cbcgame** [comment]
> 更新了，最近有点忙，不好意思 详见[Release v1.6.0](https://github.com/Xu22Web/tech-study-js/releases/tag/v1.6.0) @cbcgame

大神，感谢更新，不好意思我是个小白，我点进去了你的更新页面，还是不知道怎么操作 ，对不起，能否出个简单安装的教程@Xu22Web

**Comment by cbcgame** [comment]
![image](https://user-images.githubusercontent.com/128456518/226552402-61ef49f0-ca66-407d-983b-1f7c4e69276f.png)

请问哪位大神指导一下，这个是啥怎么操作下一步？

**Comment by Xu22Web** [comment]
![image](https://user-images.githubusercontent.com/63391451/226552781-ea2cb460-1ff3-4fca-ac00-b47c67e7111c.png)
或者
https://github.com/Xu22Web/tech-study-js/blob/master/tech-study.js

**Comment by WYJQAQ** [comment]
> ![image](https://user-images.githubusercontent.com/128456518/226552402-61ef49f0-ca66-407d-983b-1f7c4e69276f.png)
> 
> 请问哪位大神指导一下，这个是啥怎么操作下一步？
![image](https://user-images.githubusercontent.com/45073809/226604197-4a22ecc3-4ab4-4857-af07-fdfa238b4729.png)
![image](https://user-images.githubusercontent.com/45073809/226604219-55db458c-64b5-4b63-8ece-75cc063346f7.png)
![image](https://user-images.githubusercontent.com/45073809/226604243-89f88691-3892-498d-b8d2-5613318c98e8.png)
![image](https://user-images.githubusercontent.com/45073809/226604253-bcf094d0-b2ff-4799-8068-e2ec26596ae6.png)
查找原来的url，替换成新的，crtl+s保存就好了

**Comment by cbcgame** [comment]
大神，我用的是microsoft edge, 找到不这个
![image](https://user-images.githubusercontent.com/128456518/226796628-fcf10b74-35c9-4f46-8a3f-00e10b991850.png)
新手小白能否请您继续指点一下

> > ![image](https://user-images.githubusercontent.com/128456518/226552402-61ef49f0-ca66-407d-983b-1f7c4e69276f.png)
> > 请问哪位大神指导一下，这个是啥怎么操作下一步？
> 
> 找到管理面板 ![image](https://user-images.githubusercontent.com/45073809/226604197-4a22ecc3-4ab4-4857-af07-fdfa238b4729.png) 编辑 ![image](https://user-images.githubusercontent.com/45073809/226604219-55db458c-64b5-4b63-8ece-75cc063346f7.png) 查找 ![image](https://user-images.githubusercontent.com/45073809/226604243-89f88691-3892-498d-b8d2-5613318c98e8.png) ![image](https://user-images.githubusercontent.com/45073809/226604253-bcf094d0-b2ff-4799-8068-e2ec26596ae6.png) 查找原来的url，替换成新的，crtl+s保存就好了

**Comment by cbcgame** [comment]
@Xu22Web 
请您辛苦指点下，感恩感谢

**Comment by cbcgame** [comment]
不好意思，大神，我自己摸索了好久，终于找到了，已经解决了
