### ISSUE TITLE
打开后只会运行视听学习

### ISSUE THREAD

**Issue by markbeyond** [Xu22Web/tech-study-js#3]
我在扫码登陆后，只会运行视听学习，就算满分了还是会一直打开视频，只能通过手动关闭视听学习，再刷新主页才能正常从文章到答题的学习。请问这是什么原因导致的呢，能否帮忙解决一下？感谢感谢！

**Comment by Xu22Web** [comment]
@markbeyond 
已知问题，是官方新闻API的问题，已修复但未发布，因为正在测试滑动验证，到时候随新版本一起发布。

**Comment by Xu22Web** [comment]
@markbeyond  
新版本发布，可以着重测试下`只会运行视听学习`和`滑动验证`问题

**Comment by markbeyond** [comment]
好的，感谢！
