### ISSUE TITLE
1.6.5版本不能每日答题

### ISSUE THREAD

**Issue by asd102150** [Xu22Web/tech-study-js#34]
登陆就发现焦点不对了，每日登陆、文章、视频，默认这三个选项，然后答题不能选择，或者选择后不能启动。

**Comment by Xu22Web** [comment]
参考 [Release v1.7.0](https://github.com/Xu22Web/tech-study-js/releases/tag/v1.7.0)，点击重置按钮，重置下答题配置
@asd102150

**Comment by asd102150** [comment]
> 参考 [Release v1.7.0](https://github.com/Xu22Web/tech-study-js/releases/tag/v1.7.0)，点击重置按钮，重置下任务配置 @asd102150

更新到1.7可以使用了，谢谢！
