### ISSUE TITLE
笔记本电脑等小尺寸显示设备上会出现无法完整展示二维码现象，需要缩小页面，能否优化？

### ISSUE THREAD

**Issue by kylemills2022** [Xu22Web/tech-study-js#4]
测试系统win10 64位 
Firefox104.0.2 64位

**Comment by Xu22Web** [comment]
@kylemills2022 
我这边没问题，笔记本屏幕15.6，系统显示缩放100%，浏览器显示缩放100%，你那边可能系统有缩放，我优化下

**Comment by kylemills2022** [comment]
控件是浮动的，如果能跟随滚动或者把登录二维码展示在上方可能会更好。加上自动过滑动验证码的能力后脚本可谓之最强了，大佬牛皮。
