### ISSUE TITLE
The browser freezes directly after the tasks are executed.

### ISSUE THREAD

**Issue by 2ndMessiah** [Xu22Web/tech-study-js#44]
Happy New Year to you @Xu22Web!! I sincerely wish you a successful 2024 with happiness and wellness!!

As always, 2024 begins in a new try of XXQG with this nice script..but..something unusual happens this time.

The browser would freeze no matter how the auto-operation task is executed. I made attempts on two Chrome clients on Windows / Mac and it could be well reproduced.

My env is : Tempermonkey 5.0.1692 + Chromium  120.0.6099.71.2

![未命名](https://github.com/Xu22Web/tech-study-js/assets/22229188/588de198-1fab-425b-86f6-7017dde30ac2)

**Comment by sw1020** [comment]
一样的问题，MAC和Windows基本一样表现，MAC有时候还能跑几个，蛮奇怪的

**Comment by hotinewang** [comment]
一样的问题。年末先是火狐浏览器莫名其妙的不再自动跳转下一个视频/文章，新年以后又出现了谷歌浏览器无相应的情况。是不是网站做反脚本了？

**Comment by HenryUnderstood** [comment]
同样的问题，自动学几分网页就无响应了

**Comment by shXiaobo** [comment]
我解决的办法是直接回复到1.7.0版本

**Comment by sw1020** [comment]
> 我解决的办法是直接回复到1.7.0版本

的确可以了，感谢

**Comment by sw1020** [comment]
> 我解决的办法是直接回复到1.7.0版本

学了一半还是会卡住，感觉是不是服务端做了什么

**Comment by shXiaobo** [comment]
一样，等作者更新吧
