### ISSUE TITLE
大佬有几个原版功能没了，能加回去么

### ISSUE THREAD

**Issue by sunyi369** [Xu22Web/tech-study-js#6]
感谢大佬的脚本，但是好像有几个原版的功能没了，视频不自动播放了。原版的文章会自动往下滚动也没有了。

**Comment by Xu22Web** [comment]
@sunyi369 
滚动删除了，但是视频播放可以进行。原版滚动是为了触发观看事件，我已经用代码模拟了滚动事件，所以我感觉可有可无
