### ISSUE TITLE
2023/1/1没法用了开始按钮一直显示“等待中”

### ISSUE THREAD

**Issue by pengfeiweb** [Xu22Web/tech-study-js#7]
昨天还挺好。望大神尽快更新。解脱我等苦难。

**Comment by Xu22Web** [comment]
@pengfeiweb 
官方好像把`每周答题`去掉了，不知道你们是不是这个情况，如果是，我得修改下代码

**Comment by Xu22Web** [comment]
@pengfeiweb 
新版脚本 [tech-study-js v1.4.0](https://github.com/Xu22Web/tech-study-js/releases/tag/v1.4.0) 已经发布，问题基本得到解决

如仍存在问题，可以继续反馈。

**Comment by pengfeiweb** [comment]
已测试正常。至谢。如需要，请留捐赠地址。
