### ISSUE TITLE
2023.1.1无法使用，一直显示等待中

### ISSUE THREAD

**Issue by 530775859** [Xu22Web/tech-study-js#8]

**Comment by Xu22Web** [comment]
@530775859 
官方好像把`每周答题`去掉了，不知道你们是不是这个情况，如果是，我得修改下代码

**Comment by poromony** [comment]
> @530775859 官方好像把`每周答题`去掉了，不知道你们是不是这个情况，如果是，我得修改下代码

确实是去掉了，期待修复

**Comment by Xu22Web** [comment]
新版脚本 [tech-study-js v1.4.0](https://github.com/Xu22Web/tech-study-js/releases/tag/v1.4.0) 已经发布，问题基本得到解决

如仍存在问题，可以继续反馈。
